### PR TITLE
Enable custom GLSL code for meshes

### PR DESCRIPTION
**Pull request by dwlsalmeida**
This is WIP.

The basic idea is to allow users to manually input GLSL code for meshes. This gets decided on a mesh-by-mesh basis and defaults to false.

In my opinion, this is better than popping up an Blender editor, since the user may use his/her editor of choice (with syntax highlighting, etc..) as long as the resulting file gets saved as <output_dir>/<mesh_name>.(vert/frag). Also note Blender does not have a multi-line editor currently, although it is slated to land sometime in the future for Blender 2.8.

If we set on this approach, the next steps are reading the .vert and .frag files and pushing their content to the intermediary representation.

### CODE REVIEW

**Comment by dwlsalmeida** [comment]
> Looks good! How can I test it?

For now only the UI is ready. You can check it out by switching to the GLSL tab in the exporter panel.

**Comment by dwlsalmeida** [comment]
I think we can already preview this, only proper unit tests are pending

**Comment by dwlsalmeida** [comment]
Please suggest tests for this feature.

Can we retrieve the shader source code currently associated with a mesh in RAMSES?

**Comment by dwlsalmeida** [comment]
Also, for now few attributes are passed into shaders - I guess only position is passed in currently, IIRC, but this can very easily be changed. Please advise.

**Comment by dwlsalmeida** [comment]
@GENIVI-Ramses This looks awesome! Just a few comments on my side:

a) I assume we can keep this new approach still on a "mesh-by-mesh" basis, as this is how it currently works? i.e. each mesh gets their folder (which can be shared between meshes), and skips this feature if the path is empty.

b) I guess we need the default shaders? otherwise how could we render something if the user does not provide any shaders? I feel providing shader code for meshes should be optional if in the future we implement baking (easy) and/or our own implementation of Principled BSDF (hard for now). Baking should generate a ready-to-use texture and BSDF would be just a shader that takes its inputs from Blender. If we are to keep the default shaders then I suggest putting them in a folder too, so they act like a template for user defined ones.

c) This config sounds good too, but what format should we use? We can also provide checkboxes in the GUI that indicate what attribute names are available for the user-provided shader. Maybe these can coexist, so they can be either set in the GUI or generated on-the-fly by the user? I assume it will be pretty tedious to set these up in the GUI if we're talking 100s of meshes, so having a text based config means more flexibility to automate this.

**Comment by GENIVI-Ramses** [comment]
a) Shaders are usually specified per mesh, so I think a mesh-by-mesh approach is feasible. There are many ways to improve it, but for let's keep it simple - just a named-based matching of shaders to meshes. Several meshes using the same mesh would cause having to copy the shaders, but that's ok for now. I like the idea of a folder-per-mesh, I was thinking originally to put all shaders in one folder, but a subfolder is better.
b) True - we need a default shader, but for now I'd leave it directly in the python code, no need for extra file. We could replace the default shader with Principled BSDF in the future - it will be easier to do so in Python code. Also, it would be possible to override the exporter class and replace the default shader with something else, if needed. Also, this way we don't have to do special magic to copy and install the default shaders, set paths etc.
c) I would not make the GUI more advanced, for now. Just make the shader folder for the whole scene settable in the GUI (or if that's difficult, take the export target folder and look for shaders there). Regarding the config - just parse a key-value property pairs, one per line. Something like this:
u_color: vec4(1.0, 0.0, 0.0, 1.0)

**Comment by dwlsalmeida** [comment]
This should hopefully be good to go now. Tests pass.

I took a few ideas from [substanc3d](https://docs.substance3d.com/sddoc/glslfx-shaders-102400055.html#GLSLFXShaders-Techniques) for the config file. The config file is JSON. 

Leaving the directory blank in the 'mesh' menu skips this feature.

**Pull request merged**
