### PR TITLE
Implements scaling and translation ordering.

### PR DESCRIPTION
**Pull request by dwlsalmeida**
This is WIP. It is also broken at the moment.

I have been unable to load the resulting scene in the Scene Viewer and in RenderDoc.

Violin, I wonder if implementing a very simple fly mode for the RAMSES scene viewer would be something worth considering? I guess it is common to have it for programs in which you're presented a 3D viewport?

If it's not in the radar for you guys I can volunteer. I say so because a black screen due to misplaced cameras or meshes is hard to debug if one does not know what s/he's looking for.

Also, the debug log is here: https://pastebin.com/msbbRiYs but it looks correct so it is not really helpful to me..

Signed-off-by: Daniel W. S. Almeida <dwlsalmeida@gmail.com>

### CODE REVIEW

**Comment by dwlsalmeida** [comment]
Also, I feel that pasting the debug log is in order! So here it is: https://pastebin.com/msbbRiYs

**Comment by dwlsalmeida** [comment]
@violinyanev  Do you like where this is going with the last tests? Specially with the way I am computing values for scaling, rotation and translation?

By the way I just noted you said to split this up into more PRs (instead of simply more commits), I'd like some help to do so in git.

**Comment by gunnarx** [comment]
Interesting read.  For the randomized tests (like scaling),  have you also considered a special  test for boundary conditions (the limit for input values).
For example make sure to test scale=0.0.
What happens if scale is negative, or is this forbidden and is ut caught by the program.

**Comment by dwlsalmeida** [comment]
hey @gunnarx !

I was on a call with Violin earlier today and it was brought to my attention that randomized tests might sometimes hide broken things: i.e. the tests might fail randomly when the random number generator finally passes in an input that does not work. As I have agreed to give this a shot from a clean slate now (as the current approach has too many changes to point out what specifically broke) I feel these randomized tests might be phased out then in favor of deterministic ones. What do you think?

As for your question more specifically, at first I was considering raising exceptions or otherwise completely halting up, but then later on considered just putting out some kind of warning, which might get tested by mocking the logger object I guess. I say this because although I cannot think of a reason to scale by zero at my current skill level, for instance, maybe it might be something that is actually used (and in a valid way) by the Blender community. So to avoid needlessly getting in the way of users, maybe a simple warning in the logs would be more fitting!

**Comment by dwlsalmeida** [comment]
By the way, I plan on forking the last working revision of my code (that is, the master branch) to try again.  Then maybe this PR should be closed in favor of a completely new one in its place?

**Comment by violinyanev** [comment]
Sounds like a good idea :) When I say "new PR" it doesn't mean you have to rewrite the code though! Just create new branches, cherry-pick the commits (modify or split into smaller parts) and create a PR out of the new branches. Git's power lies in the juggling of commits and branches. It should become a childs play to do that - it is essential for any OSS project :) I think the code in general is good - just try to split it up a little. I am sure you can extract smaller parts of it which work, and get them in!

**Pull request closed without merging**
